/*
 * gpt2_2x4_qnn.c — QNNVerifier-style FFN verification harness
 *
 * Generated by ffn_qnn_generator.py
 *
 * Architecture: input[2] → Linear → GELU → Linear → output[2]
 *   d_model = 2,  d_ff = 4,  activation = gelu
 *
 * Method: abstract-interval (int32_t hidden, no dead pre-act code) (mirrors ACASXU_Reluplex_fxp interval injection)
 *   - fxp_t = int64_t, Q8.8 (SCALE=256) (hidden: int32_t)
 *   - Layer 1 pre-activation computed exactly in fxp arithmetic
 *   - GELU activation abstracted as interval: __ESBMC_assume(hidden[j] ∈ [lo, hi])
 *     (bounds proved analytically — equivalent to Frama-C EVA in QNNVerifier pipeline)
 *   - Layer 2: exact linear computation in fxp
 *   - Symbolic input: nondet_int() in [-256, 256] ≡ float [-1, 1]
 *
 * Verify:
 *   esbmc gpt2_2x4_qnn.c --no-unwinding-assertions --boolector
 *
 * Expected: VERIFICATION SUCCESSFUL
 */

/* ---- FXP runtime: Q8.8 — int32_t for hidden layer (values bounded << 2^31) ---- */
#include <stdint.h>
typedef int64_t fxp_t;   /* full-precision type (Layer 1 pre-act, Layer 2 acc) */
#define FRAC_BITS 8
#define SCALE     256

static fxp_t fxp_mult(fxp_t a, fxp_t b) { return (a * b) >> FRAC_BITS; }
static fxp_t fxp_add(fxp_t a, fxp_t b)  { return a + b; }
static int   fxp_to_int(fxp_t x)        { return (int)(x >> FRAC_BITS); }

/* 32-bit FXP multiply: hidden ∈ [-60,60], weights ∈ [-30,30] → product ≤ 1800 << INT32_MAX */
static int32_t fxp32_mult(int32_t a, int32_t b) { return (a * b) >> FRAC_BITS; }

/* ESBMC builtins */
int  nondet_int(void);
void __ESBMC_assume(_Bool cond);
void __ESBMC_assert(_Bool cond, const char *msg);

/* ---- W2[2][4] in Q8.8 (int32) ---- */
static int32_t W2_0[4] = { -20, 22, 21, 1 };
static int32_t W2_1[4] = { -24, 2, -23, 23 };


int main(void) {

    /* Hidden neurons: symbolic, each bounded by analytical GELU interval
     * (no Layer-1 pre-activation — inputs decoupled in abstract mode) */
    int32_t h[4];
    h[0] = nondet_int(); __ESBMC_assume(h[0] >= -9 && h[0] <= 10);
    h[1] = nondet_int(); __ESBMC_assume(h[1] >= -5 && h[1] <= 6);
    h[2] = nondet_int(); __ESBMC_assume(h[2] >= -13 && h[2] <= 15);
    h[3] = nondet_int(); __ESBMC_assume(h[3] >= -18 && h[3] <= 23);

    /* Layer 2: down-projection in Q8.8 (32-bit accumulation) */
    int32_t out0 = 0;
    out0 += fxp32_mult(W2_0[0], h[0]);
    out0 += fxp32_mult(W2_0[1], h[1]);
    out0 += fxp32_mult(W2_0[2], h[2]);
    out0 += fxp32_mult(W2_0[3], h[3]);
    int32_t out1 = 0;
    out1 += fxp32_mult(W2_1[0], h[0]);
    out1 += fxp32_mult(W2_1[1], h[1]);
    out1 += fxp32_mult(W2_1[2], h[2]);
    out1 += fxp32_mult(W2_1[3], h[3]);

    /* P1: output within analytically-derived bound ±12 (Q8.8) */
    __ESBMC_assert(out0 >= -12 && out0 <= 12, "P1: output[0] out of bound");
    __ESBMC_assert(out1 >= -12 && out1 <= 12, "P1: output[1] out of bound");

    return 0;
}
