/*
 * Fixed-Point FFN Verification Harness — auto-generated by ffn_fxp_generator.py
 *
 * Layer index   : 0
 * Dimensions    : d_model=4, d_ff=8
 * Activation    : ReLU (proxy for GeLU/SiLU)
 * Format        : Q8.8 (int16_t, SCALE=256)
 * Input range   : [-1.0, 1.0]
 *                 = [-256, 256] in Q8.8
 * Output bound  : ±15 in Q8.8 (≈ ±0.059 float)
 *
 * Verify with:
 *   esbmc gpt2_4x8.c --overflow-check \
 *       --unwind 9 --no-unwinding-assertions --z3
 *
 * Properties:
 *   P1: No integer overflow in pre-activations (via --overflow-check)
 *   P2: Pre-activations within analytical bound
 *   P3: Output within analytical bound (±15)
 *   P4: Array accesses in bounds (default ESBMC behaviour)
 */

#include <stdint.h>

#define D_MODEL 4
#define D_FF    8
#define SCALE   256

/* ---- ESBMC builtins ------------------------------------------------------ */
int nondet_int(void);
void __ESBMC_assume(_Bool cond);
void __ESBMC_assert(_Bool cond, const char *msg);

/* ---- Q8.8 fixed-point multiply ------------------------------------------ */
static int32_t fxp_mult(int32_t a, int32_t b) {
    return (a * b) >> 8;
}

/* ---- Weights: layer 0, quantised to Q8.8 ---------- */
static int16_t W1[D_FF][D_MODEL] = {
    { 2, -5, 4, 5 },
    { -7, 9, 9, 7 },
    { 4, -9, -5, 8 },
    { 2, -3, 10, 0 },
    { -8, 4, 6, -4 },
    { -7, 0, 2, 9 },
    { -6, -2, 0, 10 },
    { 0, -2, -1, 5 }
};
static int16_t b1[D_FF]          = { 0, 0, 0, 0, 0, 0, 0, 0 };
static int16_t W2[D_MODEL][D_FF] = {
    { 6, 6, 4, -1, 2, -3, -4, -3 },
    { 9, -5, -5, -3, -2, 2, 1, -3 },
    { 3, 1, -5, -3, -2, 2, 5, -7 },
    { 1, -3, -1, -4, -1, 1, 5, -6 }
};
static int16_t b2[D_MODEL]       = { 0, 0, 0, 0 };

/* ---- Verification entry point ------------------------------------------- */
int main(void) {

    /* Symbolic input in Q8.8 ∈ [-256, 256] */
    int32_t input[D_MODEL];
    for (int i = 0; i < D_MODEL; i++) {
        input[i] = nondet_int();
        __ESBMC_assume(input[i] >= -256 && input[i] <= 256);
    }

    /* --- Layer 1: up-projection ------------------------------------------ */
    int32_t pre_act[D_FF];
    for (int j = 0; j < D_FF; j++) {
        int32_t acc = (int32_t)b1[j];
        for (int i = 0; i < D_MODEL; i++) {
            acc += fxp_mult((int32_t)W1[j][i], input[i]);
        }
        pre_act[j] = acc;
    }

    /* P2: pre-activations bounded */
    for (int j = 0; j < D_FF; j++) {
        __ESBMC_assert(pre_act[j] >= -41 &&
                       pre_act[j] <= 41,
                       "P2: hidden pre-activation out of range");
    }

    /* Activation: ReLU (conservative proxy for GELU) */
    int32_t hidden[D_FF];
    for (int j = 0; j < D_FF; j++) {
        hidden[j] = pre_act[j] > 0 ? pre_act[j] : 0;
    }

    /* --- Layer 2: down-projection ---------------------------------------- */
    int32_t output[D_MODEL];
    for (int k = 0; k < D_MODEL; k++) {
        int32_t acc = (int32_t)b2[k];
        for (int j = 0; j < D_FF; j++) {
            acc += fxp_mult((int32_t)W2[k][j], hidden[j]);
        }
        output[k] = acc;
    }

    /* P3: output within analytical bound */
    for (int k = 0; k < D_MODEL; k++) {
        __ESBMC_assert(output[k] >= -15 && output[k] <= 15,
                       "P3: output out of bound");
    }

    return 0;
}
