/*
 * gpt2_4x16_qnn.c — QNNVerifier-style FFN verification harness
 *
 * Generated by ffn_qnn_generator.py
 *
 * Architecture: input[4] → Linear → GELU → Linear → output[4]
 *   d_model = 4,  d_ff = 16,  activation = gelu
 *
 * Method: abstract-interval (mirrors ACASXU_Reluplex_fxp interval injection)
 *   - fxp_t = int64_t, Q8.8 (SCALE=256)
 *   - Layer 1 pre-activation computed exactly in fxp arithmetic
 *   - GELU activation abstracted as interval: __ESBMC_assume(hidden[j] ∈ [lo, hi])
 *     (bounds proved analytically — equivalent to Frama-C EVA in QNNVerifier pipeline)
 *   - Layer 2: exact linear computation in fxp
 *   - Symbolic input: nondet_int() in [-256, 256] ≡ float [-1, 1]
 *
 * Verify:
 *   esbmc gpt2_4x16_qnn.c --overflow-check --no-unwinding-assertions --z3
 *
 * Expected: VERIFICATION SUCCESSFUL
 */

/* ---- FXP runtime: Q8.8, int64_t, SCALE=256 ---- */
#include <stdint.h>
typedef int64_t fxp_t;
#define FRAC_BITS 8
#define SCALE     256

static fxp_t fxp_mult(fxp_t a, fxp_t b) { return (a * b) >> FRAC_BITS; }
static fxp_t fxp_add(fxp_t a, fxp_t b)  { return a + b; }
static int   fxp_to_int(fxp_t x)        { return (int)(x >> FRAC_BITS); }

/* ESBMC builtins */
int  nondet_int(void);
void __ESBMC_assume(_Bool cond);
void __ESBMC_assert(_Bool cond, const char *msg);

/* ---- W1[16][4] in Q8.8 ---- */
static fxp_t W1_0[4] = { 14LL, -3LL, 19LL, 10LL };
static fxp_t W1_1[4] = { 7LL, 3LL, 3LL, -10LL };
static fxp_t W1_2[4] = { -21LL, 5LL, -17LL, 22LL };
static fxp_t W1_3[4] = { -20LL, 17LL, -18LL, -17LL };
static fxp_t W1_4[4] = { 17LL, -21LL, -23LL, 5LL };
static fxp_t W1_5[4] = { 22LL, -1LL, -9LL, 2LL };
static fxp_t W1_6[4] = { -6LL, 25LL, 11LL, 24LL };
static fxp_t W1_7[4] = { -23LL, 6LL, -24LL, 20LL };
static fxp_t W1_8[4] = { -23LL, -11LL, -9LL, -17LL };
static fxp_t W1_9[4] = { 21LL, 5LL, 18LL, -8LL };
static fxp_t W1_10[4] = { 13LL, 16LL, -24LL, -14LL };
static fxp_t W1_11[4] = { -11LL, 3LL, 15LL, 15LL };
static fxp_t W1_12[4] = { -20LL, 6LL, -14LL, 4LL };
static fxp_t W1_13[4] = { -5LL, 9LL, 12LL, 3LL };
static fxp_t W1_14[4] = { -12LL, -16LL, -16LL, 1LL };
static fxp_t W1_15[4] = { 2LL, -3LL, -19LL, -20LL };

/* ---- b1[16] in Q8.8 ---- */
static fxp_t B1[16] = { 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL };

/* ---- W2[4][16] in Q8.8 ---- */
static fxp_t W2_0[16] = { -20LL, 22LL, 21LL, 1LL, 7LL, -15LL, -3LL, -16LL, -25LL, 25LL, -13LL, 5LL, -10LL, -7LL, -5LL, -9LL };
static fxp_t W2_1[16] = { -24LL, 2LL, -23LL, 23LL, 19LL, -15LL, 10LL, 4LL, 16LL, -1LL, -16LL, 7LL, -22LL, 4LL, -15LL, 10LL };
static fxp_t W2_2[16] = { -20LL, 15LL, 23LL, -21LL, -18LL, 25LL, -16LL, -22LL, 24LL, 21LL, 8LL, 3LL, 22LL, 8LL, 8LL, 18LL };
static fxp_t W2_3[16] = { -25LL, -13LL, 6LL, -18LL, 4LL, -7LL, 2LL, -26LL, 18LL, -7LL, -19LL, -3LL, -1LL, 7LL, 1LL, -24LL };

/* ---- b2[4] in Q8.8 ---- */
static fxp_t B2[4] = { 0LL, 0LL, 0LL, 0LL };

int main(void) {

    /* Symbolic input in Q8.8: [-256, 256] ≡ float [-1, 1] */
    fxp_t input[4];
    input[0] = (fxp_t)nondet_int();
    __ESBMC_assume(input[0] >= -256LL && input[0] <= 256LL);
    input[1] = (fxp_t)nondet_int();
    __ESBMC_assume(input[1] >= -256LL && input[1] <= 256LL);
    input[2] = (fxp_t)nondet_int();
    __ESBMC_assume(input[2] >= -256LL && input[2] <= 256LL);
    input[3] = (fxp_t)nondet_int();
    __ESBMC_assume(input[3] >= -256LL && input[3] <= 256LL);

    /* Layer 1: up-projection + GELU — QNNVerifier per-neuron interval injection */
    fxp_t hidden[16];
    {
        /* Neuron 0: pre-activation dot product */
        fxp_t acc = B1[0];
        acc = fxp_add(acc, fxp_mult(W1_0[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_0[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_0[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_0[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[0] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[0] >= -22LL && hidden[0] <= 29LL);
    {
        /* Neuron 1: pre-activation dot product */
        fxp_t acc = B1[1];
        acc = fxp_add(acc, fxp_mult(W1_1[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_1[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_1[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_1[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[1] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[1] >= -12LL && hidden[1] <= 14LL);
    {
        /* Neuron 2: pre-activation dot product */
        fxp_t acc = B1[2];
        acc = fxp_add(acc, fxp_mult(W1_2[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_2[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_2[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_2[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[2] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[2] >= -28LL && hidden[2] <= 43LL);
    {
        /* Neuron 3: pre-activation dot product */
        fxp_t acc = B1[3];
        acc = fxp_add(acc, fxp_mult(W1_3[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_3[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_3[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_3[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[3] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[3] >= -31LL && hidden[3] <= 48LL);
    {
        /* Neuron 4: pre-activation dot product */
        fxp_t acc = B1[4];
        acc = fxp_add(acc, fxp_mult(W1_4[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_4[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_4[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_4[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[4] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[4] >= -29LL && hidden[4] <= 43LL);
    {
        /* Neuron 5: pre-activation dot product */
        fxp_t acc = B1[5];
        acc = fxp_add(acc, fxp_mult(W1_5[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_5[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_5[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_5[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[5] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[5] >= -17LL && hidden[5] <= 20LL);
    {
        /* Neuron 6: pre-activation dot product */
        fxp_t acc = B1[6];
        acc = fxp_add(acc, fxp_mult(W1_6[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_6[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_6[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_6[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[6] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[6] >= -29LL && hidden[6] <= 44LL);
    {
        /* Neuron 7: pre-activation dot product */
        fxp_t acc = B1[7];
        acc = fxp_add(acc, fxp_mult(W1_7[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_7[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_7[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_7[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[7] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[7] >= -31LL && hidden[7] <= 49LL);
    {
        /* Neuron 8: pre-activation dot product */
        fxp_t acc = B1[8];
        acc = fxp_add(acc, fxp_mult(W1_8[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_8[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_8[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_8[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[8] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[8] >= -27LL && hidden[8] <= 39LL);
    {
        /* Neuron 9: pre-activation dot product */
        fxp_t acc = B1[9];
        acc = fxp_add(acc, fxp_mult(W1_9[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_9[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_9[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_9[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[9] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[9] >= -24LL && hidden[9] <= 34LL);
    {
        /* Neuron 10: pre-activation dot product */
        fxp_t acc = B1[10];
        acc = fxp_add(acc, fxp_mult(W1_10[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_10[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_10[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_10[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[10] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[10] >= -29LL && hidden[10] <= 43LL);
    {
        /* Neuron 11: pre-activation dot product */
        fxp_t acc = B1[11];
        acc = fxp_add(acc, fxp_mult(W1_11[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_11[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_11[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_11[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[11] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[11] >= -21LL && hidden[11] <= 28LL);
    {
        /* Neuron 12: pre-activation dot product */
        fxp_t acc = B1[12];
        acc = fxp_add(acc, fxp_mult(W1_12[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_12[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_12[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_12[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[12] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[12] >= -21LL && hidden[12] <= 27LL);
    {
        /* Neuron 13: pre-activation dot product */
        fxp_t acc = B1[13];
        acc = fxp_add(acc, fxp_mult(W1_13[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_13[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_13[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_13[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[13] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[13] >= -15LL && hidden[13] <= 18LL);
    {
        /* Neuron 14: pre-activation dot product */
        fxp_t acc = B1[14];
        acc = fxp_add(acc, fxp_mult(W1_14[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_14[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_14[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_14[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[14] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[14] >= -21LL && hidden[14] <= 28LL);
    {
        /* Neuron 15: pre-activation dot product */
        fxp_t acc = B1[15];
        acc = fxp_add(acc, fxp_mult(W1_15[0], input[0]));
        acc = fxp_add(acc, fxp_mult(W1_15[1], input[1]));
        acc = fxp_add(acc, fxp_mult(W1_15[2], input[2]));
        acc = fxp_add(acc, fxp_mult(W1_15[3], input[3]));
        (void)acc;  /* pre-act computed; activation abstracted below */
        hidden[15] = (fxp_t)nondet_int();
    }
    /* GELU interval (proved analytically, mirrors Frama-C EVA output): */
    __ESBMC_assume(hidden[15] >= -21LL && hidden[15] <= 28LL);

    /* Layer 2: down-projection (linear) */
    fxp_t output[4];
    {
        fxp_t acc = B2[0];
        acc = fxp_add(acc, fxp_mult(W2_0[0], hidden[0]));
        acc = fxp_add(acc, fxp_mult(W2_0[1], hidden[1]));
        acc = fxp_add(acc, fxp_mult(W2_0[2], hidden[2]));
        acc = fxp_add(acc, fxp_mult(W2_0[3], hidden[3]));
        acc = fxp_add(acc, fxp_mult(W2_0[4], hidden[4]));
        acc = fxp_add(acc, fxp_mult(W2_0[5], hidden[5]));
        acc = fxp_add(acc, fxp_mult(W2_0[6], hidden[6]));
        acc = fxp_add(acc, fxp_mult(W2_0[7], hidden[7]));
        acc = fxp_add(acc, fxp_mult(W2_0[8], hidden[8]));
        acc = fxp_add(acc, fxp_mult(W2_0[9], hidden[9]));
        acc = fxp_add(acc, fxp_mult(W2_0[10], hidden[10]));
        acc = fxp_add(acc, fxp_mult(W2_0[11], hidden[11]));
        acc = fxp_add(acc, fxp_mult(W2_0[12], hidden[12]));
        acc = fxp_add(acc, fxp_mult(W2_0[13], hidden[13]));
        acc = fxp_add(acc, fxp_mult(W2_0[14], hidden[14]));
        acc = fxp_add(acc, fxp_mult(W2_0[15], hidden[15]));
        output[0] = acc;
    }
    {
        fxp_t acc = B2[1];
        acc = fxp_add(acc, fxp_mult(W2_1[0], hidden[0]));
        acc = fxp_add(acc, fxp_mult(W2_1[1], hidden[1]));
        acc = fxp_add(acc, fxp_mult(W2_1[2], hidden[2]));
        acc = fxp_add(acc, fxp_mult(W2_1[3], hidden[3]));
        acc = fxp_add(acc, fxp_mult(W2_1[4], hidden[4]));
        acc = fxp_add(acc, fxp_mult(W2_1[5], hidden[5]));
        acc = fxp_add(acc, fxp_mult(W2_1[6], hidden[6]));
        acc = fxp_add(acc, fxp_mult(W2_1[7], hidden[7]));
        acc = fxp_add(acc, fxp_mult(W2_1[8], hidden[8]));
        acc = fxp_add(acc, fxp_mult(W2_1[9], hidden[9]));
        acc = fxp_add(acc, fxp_mult(W2_1[10], hidden[10]));
        acc = fxp_add(acc, fxp_mult(W2_1[11], hidden[11]));
        acc = fxp_add(acc, fxp_mult(W2_1[12], hidden[12]));
        acc = fxp_add(acc, fxp_mult(W2_1[13], hidden[13]));
        acc = fxp_add(acc, fxp_mult(W2_1[14], hidden[14]));
        acc = fxp_add(acc, fxp_mult(W2_1[15], hidden[15]));
        output[1] = acc;
    }
    {
        fxp_t acc = B2[2];
        acc = fxp_add(acc, fxp_mult(W2_2[0], hidden[0]));
        acc = fxp_add(acc, fxp_mult(W2_2[1], hidden[1]));
        acc = fxp_add(acc, fxp_mult(W2_2[2], hidden[2]));
        acc = fxp_add(acc, fxp_mult(W2_2[3], hidden[3]));
        acc = fxp_add(acc, fxp_mult(W2_2[4], hidden[4]));
        acc = fxp_add(acc, fxp_mult(W2_2[5], hidden[5]));
        acc = fxp_add(acc, fxp_mult(W2_2[6], hidden[6]));
        acc = fxp_add(acc, fxp_mult(W2_2[7], hidden[7]));
        acc = fxp_add(acc, fxp_mult(W2_2[8], hidden[8]));
        acc = fxp_add(acc, fxp_mult(W2_2[9], hidden[9]));
        acc = fxp_add(acc, fxp_mult(W2_2[10], hidden[10]));
        acc = fxp_add(acc, fxp_mult(W2_2[11], hidden[11]));
        acc = fxp_add(acc, fxp_mult(W2_2[12], hidden[12]));
        acc = fxp_add(acc, fxp_mult(W2_2[13], hidden[13]));
        acc = fxp_add(acc, fxp_mult(W2_2[14], hidden[14]));
        acc = fxp_add(acc, fxp_mult(W2_2[15], hidden[15]));
        output[2] = acc;
    }
    {
        fxp_t acc = B2[3];
        acc = fxp_add(acc, fxp_mult(W2_3[0], hidden[0]));
        acc = fxp_add(acc, fxp_mult(W2_3[1], hidden[1]));
        acc = fxp_add(acc, fxp_mult(W2_3[2], hidden[2]));
        acc = fxp_add(acc, fxp_mult(W2_3[3], hidden[3]));
        acc = fxp_add(acc, fxp_mult(W2_3[4], hidden[4]));
        acc = fxp_add(acc, fxp_mult(W2_3[5], hidden[5]));
        acc = fxp_add(acc, fxp_mult(W2_3[6], hidden[6]));
        acc = fxp_add(acc, fxp_mult(W2_3[7], hidden[7]));
        acc = fxp_add(acc, fxp_mult(W2_3[8], hidden[8]));
        acc = fxp_add(acc, fxp_mult(W2_3[9], hidden[9]));
        acc = fxp_add(acc, fxp_mult(W2_3[10], hidden[10]));
        acc = fxp_add(acc, fxp_mult(W2_3[11], hidden[11]));
        acc = fxp_add(acc, fxp_mult(W2_3[12], hidden[12]));
        acc = fxp_add(acc, fxp_mult(W2_3[13], hidden[13]));
        acc = fxp_add(acc, fxp_mult(W2_3[14], hidden[14]));
        acc = fxp_add(acc, fxp_mult(W2_3[15], hidden[15]));
        output[3] = acc;
    }

    /* P1: output within analytically-derived bound ±56 (Q8.8) */
    __ESBMC_assert(output[0] >= -56LL && output[0] <= 56LL, "P1: output[0] out of bound");
    __ESBMC_assert(output[1] >= -56LL && output[1] <= 56LL, "P1: output[1] out of bound");
    __ESBMC_assert(output[2] >= -56LL && output[2] <= 56LL, "P1: output[2] out of bound");
    __ESBMC_assert(output[3] >= -56LL && output[3] <= 56LL, "P1: output[3] out of bound");

    return 0;
}
