/*
 * Fixed-Point FFN Verification Harness — auto-generated by ffn_fxp_generator.py
 *
 * Layer index   : 0
 * Dimensions    : d_model=8, d_ff=32
 * Activation    : ReLU (proxy for GeLU/SiLU)
 * Format        : Q8.8 (int16_t, SCALE=256)
 * Input range   : [-1.0, 1.0]
 *                 = [-256, 256] in Q8.8
 * Output bound  : ±143 in Q8.8 (≈ ±0.559 float)
 *
 * Verify with:
 *   esbmc llama_fxp.c --overflow-check \
 *       --unwind 33 --no-unwinding-assertions --z3
 *
 * Properties:
 *   P1: No integer overflow in pre-activations (via --overflow-check)
 *   P2: Pre-activations within analytical bound
 *   P3: Output within analytical bound (±143)
 *   P4: Array accesses in bounds (default ESBMC behaviour)
 */

#include <stdint.h>

#define D_MODEL 8
#define D_FF    32
#define SCALE   256

/* ---- ESBMC builtins ------------------------------------------------------ */
int nondet_int(void);
void __ESBMC_assume(_Bool cond);
void __ESBMC_assert(_Bool cond, const char *msg);

/* ---- Q8.8 fixed-point multiply ------------------------------------------ */
static int32_t fxp_mult(int32_t a, int32_t b) {
    return (a * b) >> 8;
}

/* ---- Weights: layer 0, quantised to Q8.8 ---------- */
static int16_t W1[D_FF][D_MODEL] = {
    { 2, -5, 4, 5, -10, -7, 1, -2 },
    { 3, 4, 2, -1, 3, 1, -4, 9 },
    { 3, -3, 6, -3, 1, -7, -5, 0 },
    { -2, 9, -3, 4, 6, 0, 1, -9 },
    { 3, -8, 2, 3, -12, 1, 4, 3 },
    { -6, -9, 0, 7, 2, 9, 7, 0 },
    { 1, -1, 1, -8, 3, -2, 1, -10 },
    { -5, -4, 4, -7, -4, -5, 4, -4 },
    { 2, 9, 2, -5, -7, -7, 0, -2 },
    { 5, -1, 4, 3, 9, 0, -2, -3 },
    { 2, 6, 1, 3, -3, 4, -3, -6 },
    { 3, 5, -2, 9, 11, 6, 6, -9 },
    { 3, 2, 2, -4, 6, -1, 1, 2 },
    { -4, 5, 8, 1, 0, 4, 1, 6 },
    { 2, 3, -6, 7, -2, -5, 5, 7 },
    { -5, 4, -6, -4, -6, -2, 3, 1 },
    { -9, 4, -1, 0, -3, 4, 1, -6 },
    { -1, -3, 7, 2, -9, 0, -2, -13 },
    { -8, -7, 0, -9, 4, 1, 10, 2 },
    { -9, 7, 1, 3, 7, -1, -1, -6 },
    { -3, -3, -4, -6, -11, 4, 1, 11 },
    { 0, 5, -6, 4, 5, -1, 7, -1 },
    { 2, -11, -13, -1, 9, -5, 4, 2 },
    { -4, 0, 2, -3, -8, 3, 3, 8 },
    { 10, -10, 7, 1, -5, 5, -5, 7 },
    { -8, 0, -6, -3, 1, -11, 2, 4 },
    { 1, -5, 1, 4, -1, -3, 7, 6 },
    { 12, 6, -2, -4, -4, -4, -5, 0 },
    { 0, -2, 9, 0, -6, 3, 9, 4 },
    { -4, -1, 4, 0, -8, -6, -10, -1 },
    { -6, -4, -1, -8, 6, 0, -6, 0 },
    { 1, 6, 1, 3, -5, -10, 7, 3 }
};
static int16_t b1[D_FF]          = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static int16_t W2[D_MODEL][D_FF] = {
    { -2, -5, 5, 3, 1, -1, 5, -4, -1, 0, 1, 2, -3, -4, 1, 4, -4, -2, 3, 2, 1, 0, 3, 0, 2, -3, -1, 0, -8, -3, -2, 0 },
    { -2, 4, -5, -3, 3, -2, 1, 0, -4, 4, 4, -2, -2, -1, 2, 6, 3, 4, 7, 1, 3, -1, -4, -1, 1, 6, -2, 5, -6, 1, 1, -3 },
    { 0, 0, 4, -3, 3, -1, 4, -2, 5, 4, 4, -1, 4, 1, 0, 1, -2, 2, 6, 1, 3, -3, -3, 4, 3, 0, -1, 2, 1, 8, 3, -8 },
    { -3, 0, 0, 1, 3, 1, -1, -7, 4, 8, -5, -1, -1, 2, 0, -5, 5, -8, 3, 7, 4, 0, -4, -1, -1, 4, -7, 1, 0, 2, 7, 4 },
    { 5, 1, 1, 1, 7, -3, -2, 2, -4, 0, 1, -3, 2, 2, 2, 2, 0, 0, -2, 6, 1, 7, 1, -1, 4, -2, 7, -2, -8, 6, 3, -1 },
    { -2, -4, 2, -2, 1, -1, -1, 2, 0, 0, 4, -4, -7, -4, -2, 2, -1, 0, 0, 1, 2, 2, 1, -2, -1, -1, 2, 5, -3, -1, 0, -7 },
    { 9, 0, -5, -4, 5, 1, -2, 8, 3, 2, 4, 0, 6, -5, 5, 9, 1, -4, -2, -1, -1, -1, -1, -2, -6, -1, -3, -4, -1, -3, -6, 1 },
    { 1, 0, 1, -5, 1, -3, 0, 0, 3, 6, -4, 2, 4, -2, 1, 5, 0, -5, -2, -6, -3, 1, 6, 0, -3, 1, -2, -1, 0, 0, -1, -1 }
};
static int16_t b2[D_MODEL]       = { 0, 0, 0, 0, 0, 0, 0, 0 };

/* ---- Verification entry point ------------------------------------------- */
int main(void) {

    /* Symbolic input in Q8.8 ∈ [-256, 256] */
    int32_t input[D_MODEL];
    for (int i = 0; i < D_MODEL; i++) {
        input[i] = nondet_int();
        __ESBMC_assume(input[i] >= -256 && input[i] <= 256);
    }

    /* --- Layer 1: up-projection ------------------------------------------ */
    int32_t pre_act[D_FF];
    for (int j = 0; j < D_FF; j++) {
        int32_t acc = (int32_t)b1[j];
        for (int i = 0; i < D_MODEL; i++) {
            acc += fxp_mult((int32_t)W1[j][i], input[i]);
        }
        pre_act[j] = acc;
    }

    /* P2: pre-activations bounded */
    for (int j = 0; j < D_FF; j++) {
        __ESBMC_assert(pre_act[j] >= -105 &&
                       pre_act[j] <= 105,
                       "P2: hidden pre-activation out of range");
    }

    /* Activation: ReLU (conservative proxy for SILU) */
    int32_t hidden[D_FF];
    for (int j = 0; j < D_FF; j++) {
        hidden[j] = pre_act[j] > 0 ? pre_act[j] : 0;
    }

    /* --- Layer 2: down-projection ---------------------------------------- */
    int32_t output[D_MODEL];
    for (int k = 0; k < D_MODEL; k++) {
        int32_t acc = (int32_t)b2[k];
        for (int j = 0; j < D_FF; j++) {
            acc += fxp_mult((int32_t)W2[k][j], hidden[j]);
        }
        output[k] = acc;
    }

    /* P3: output within analytical bound */
    for (int k = 0; k < D_MODEL; k++) {
        __ESBMC_assert(output[k] >= -143 && output[k] <= 143,
                       "P3: output out of bound");
    }

    return 0;
}
