"""
Generate a fixed-point (Q8.8 INT16) C verification harness for one FFN layer.

Fixed-point arithmetic is dramatically faster for ESBMC than --floatbv because
it reduces to bit-vector arithmetic, which Z3/Bitwuzla handle efficiently.

Format Q8.8
-----------
  SCALE = 256  (2^8 fractional bits)
  float_to_fxp(v)  = int16_t(round(v * 256))
  fxp_mult(a, b)   = (int32_t)(a * b) >> 8   (rescale after multiply)
  fxp_add(a, b)    = a + b

Activation (ReLU, GeLU-approx, or SiLU-approx)
-----------------------------------------------
  ReLU(x)       = max(x, 0)                       ← trivial for ESBMC
  GeLU-approx   = x if x>0, else 0  (ReLU proxy) ← conservative, tractable
  SiLU-approx   = x if x>0, else 0  (ReLU proxy) ← conservative, tractable

The ReLU proxy is an over-approximation for formal bounds: if output is bounded
under ReLU, it is also bounded under GeLU/SiLU (which are strictly between
ReLU and the identity for positive inputs, and saturate near 0 for negatives).

Usage
-----
  python ffn_fxp_generator.py gpt2_ffn.onnx --layer 0 \\
      --d-model-max 8 --d-ff-max 32 --out verify_output/gpt2_fxp.c
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional

import numpy as np

from onnx_ffn_extractor import FFNLayer


SCALE = 256  # Q8.8 fractional scale


def _float_to_q88(v: float) -> int:
    """Convert float to Q8.8 int16, clamped to int16 range."""
    raw = int(round(v * SCALE))
    return max(-32768, min(32767, raw))


def _bound_comment(W: np.ndarray, input_bound_fxp: int, d_in: int) -> int:
    """Conservative output bound in Q8.8 after one linear layer."""
    max_w = int(np.max(np.abs(W)) * SCALE)
    # Each neuron: sum of d_in multiplications, each ≤ max_w * input_bound / SCALE
    return d_in * max_w * input_bound_fxp // SCALE + 1


def generate_fxp_c(
    layer: FFNLayer,
    output_path: str,
    input_bound_float: float = 1.0,
    use_relu_proxy: bool = True,
) -> str:
    """
    Generate a fixed-point ESBMC harness for *layer*.

    Parameters
    ----------
    layer             : FFNLayer with float32 weights (will be quantised here)
    output_path       : where to write the .c file
    input_bound_float : input ∈ [-input_bound_float, input_bound_float]
    use_relu_proxy    : use ReLU as conservative proxy for GeLU/SiLU

    Returns the C source as a string.
    """
    D_MODEL = layer.d_model
    D_FF    = layer.d_ff

    input_fxp = _float_to_q88(input_bound_float)

    # Quantise weights to int16 Q8.8
    W1_q = [[_float_to_q88(float(layer.W1[j, i])) for i in range(D_MODEL)]
            for j in range(D_FF)]
    b1_q = [_float_to_q88(float(layer.b1[j])) for j in range(D_FF)]
    W2_q = [[_float_to_q88(float(layer.W2[k, j])) for j in range(D_FF)]
            for k in range(D_MODEL)]
    b2_q = [_float_to_q88(float(layer.b2[k])) for k in range(D_MODEL)]

    # Compute conservative bounds
    pre_act_bound = _bound_comment(layer.W1, input_fxp, D_MODEL) + max(map(abs, b1_q))
    hidden_bound  = pre_act_bound  # ReLU ≤ identity
    out_bound     = _bound_comment(layer.W2, hidden_bound, D_FF) + max(map(abs, b2_q))
    out_safe      = int(out_bound * 1.2) + 1

    # Format helpers
    def w1_row(j):
        return "{ " + ", ".join(str(v) for v in W1_q[j]) + " }"
    def w2_row(k):
        return "{ " + ", ".join(str(v) for v in W2_q[k]) + " }"

    W1_lit = "{\n" + ",\n".join("    " + w1_row(j) for j in range(D_FF)) + "\n}"
    b1_lit = "{ " + ", ".join(str(v) for v in b1_q) + " }"
    W2_lit = "{\n" + ",\n".join("    " + w2_row(k) for k in range(D_MODEL)) + "\n}"
    b2_lit = "{ " + ", ".join(str(v) for v in b2_q) + " }"

    act_name   = "ReLU (proxy for GeLU/SiLU)" if use_relu_proxy else "ReLU"
    unwind     = max(D_FF, D_MODEL) + 1

    src = f"""\
/*
 * Fixed-Point FFN Verification Harness — auto-generated by ffn_fxp_generator.py
 *
 * Layer index   : {layer.source_layer_idx}
 * Dimensions    : d_model={D_MODEL}, d_ff={D_FF}
 * Activation    : {act_name}
 * Format        : Q8.8 (int16_t, SCALE=256)
 * Input range   : [{-input_bound_float}, {input_bound_float}]
 *                 = [{-input_fxp}, {input_fxp}] in Q8.8
 * Output bound  : ±{out_safe} in Q8.8 (≈ ±{out_safe/SCALE:.3f} float)
 *
 * Verify with:
 *   esbmc {Path(output_path).name} --overflow-check \\
 *       --unwind {unwind} --no-unwinding-assertions --z3
 *
 * Properties:
 *   P1: No integer overflow in pre-activations (via --overflow-check)
 *   P2: Pre-activations within analytical bound
 *   P3: Output within analytical bound (±{out_safe})
 *   P4: Array accesses in bounds (default ESBMC behaviour)
 */

#include <stdint.h>

#define D_MODEL {D_MODEL}
#define D_FF    {D_FF}
#define SCALE   256

/* ---- ESBMC builtins ------------------------------------------------------ */
int nondet_int(void);
void __ESBMC_assume(_Bool cond);
void __ESBMC_assert(_Bool cond, const char *msg);

/* ---- Q8.8 fixed-point multiply ------------------------------------------ */
static int32_t fxp_mult(int32_t a, int32_t b) {{
    return (a * b) >> 8;
}}

/* ---- Weights: layer {layer.source_layer_idx}, quantised to Q8.8 ---------- */
static int16_t W1[D_FF][D_MODEL] = {W1_lit};
static int16_t b1[D_FF]          = {b1_lit};
static int16_t W2[D_MODEL][D_FF] = {W2_lit};
static int16_t b2[D_MODEL]       = {b2_lit};

/* ---- Verification entry point ------------------------------------------- */
int main(void) {{

    /* Symbolic input in Q8.8 ∈ [{-input_fxp}, {input_fxp}] */
    int32_t input[D_MODEL];
    for (int i = 0; i < D_MODEL; i++) {{
        input[i] = nondet_int();
        __ESBMC_assume(input[i] >= {-input_fxp} && input[i] <= {input_fxp});
    }}

    /* --- Layer 1: up-projection ------------------------------------------ */
    int32_t pre_act[D_FF];
    for (int j = 0; j < D_FF; j++) {{
        int32_t acc = (int32_t)b1[j];
        for (int i = 0; i < D_MODEL; i++) {{
            acc += fxp_mult((int32_t)W1[j][i], input[i]);
        }}
        pre_act[j] = acc;
    }}

    /* P2: pre-activations bounded */
    for (int j = 0; j < D_FF; j++) {{
        __ESBMC_assert(pre_act[j] >= {-pre_act_bound} &&
                       pre_act[j] <= {pre_act_bound},
                       "P2: hidden pre-activation out of range");
    }}

    /* Activation: ReLU (conservative proxy for {layer.activation.upper()}) */
    int32_t hidden[D_FF];
    for (int j = 0; j < D_FF; j++) {{
        hidden[j] = pre_act[j] > 0 ? pre_act[j] : 0;
    }}

    /* --- Layer 2: down-projection ---------------------------------------- */
    int32_t output[D_MODEL];
    for (int k = 0; k < D_MODEL; k++) {{
        int32_t acc = (int32_t)b2[k];
        for (int j = 0; j < D_FF; j++) {{
            acc += fxp_mult((int32_t)W2[k][j], hidden[j]);
        }}
        output[k] = acc;
    }}

    /* P3: output within analytical bound */
    for (int k = 0; k < D_MODEL; k++) {{
        __ESBMC_assert(output[k] >= {-out_safe} && output[k] <= {out_safe},
                       "P3: output out of bound");
    }}

    return 0;
}}
"""
    Path(output_path).write_text(src)
    print(
        f"Fixed-point harness → {output_path}\n"
        f"  d_model={D_MODEL}, d_ff={D_FF}, format=Q8.8\n"
        f"  pre_act bound: ±{pre_act_bound}  output bound: ±{out_safe}\n"
        f"  Run: esbmc {Path(output_path).name} --overflow-check "
        f"--unwind {unwind} --no-unwinding-assertions --z3"
    )
    return src


if __name__ == "__main__":
    import argparse, sys
    p = argparse.ArgumentParser(description="Generate fixed-point ESBMC harness for FFN")
    p.add_argument("onnx", help="Path to .onnx model")
    p.add_argument("--layer",        type=int,   default=0)
    p.add_argument("--d-model-max",  type=int,   default=8)
    p.add_argument("--d-ff-max",     type=int,   default=32)
    p.add_argument("--input-bound",  type=float, default=1.0)
    p.add_argument("--out", default="ffn_fxp_verify.c")
    args = p.parse_args()

    from onnx_ffn_extractor import extract_ffn
    layer = extract_ffn(args.onnx, args.layer, args.d_model_max, args.d_ff_max)
    generate_fxp_c(layer, args.out, args.input_bound)
