"""
Generate a C header with a GeLU lookup table for use in ESBMC verification.

GeLU(x) = 0.5 * x * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))

LUT covers [-5, 5] in LUT_SIZE steps.
  x <  -5  →  returns 0.0  (GeLU saturates to 0 for very negative inputs)
  x >   5  →  returns x    (GeLU ≈ identity for large positive inputs)

Usage:
    python gelu_lut_gen.py                    # writes gelu_lut.h
    python gelu_lut_gen.py --output path.h
"""

import math
from pathlib import Path

LUT_MIN: float = -5.0
LUT_MAX: float = 5.0
LUT_SIZE: int = 1000   # 1000 entries → step = 0.01 per entry


def _gelu(x: float) -> float:
    inner = math.sqrt(2.0 / math.pi) * (x + 0.044715 * x ** 3)
    return 0.5 * x * (1.0 + math.tanh(inner))


def generate(output_path: str = "gelu_lut.h") -> None:
    step = (LUT_MAX - LUT_MIN) / LUT_SIZE
    values = [_gelu(LUT_MIN + i * step) for i in range(LUT_SIZE)]

    # Format 8 values per row for readability
    rows = []
    for i in range(0, LUT_SIZE, 8):
        chunk = values[i : i + 8]
        rows.append("    " + ", ".join(f"{v:.6f}f" for v in chunk))
    body = ",\n".join(rows)

    header = f"""\
#ifndef GELU_LUT_H
#define GELU_LUT_H

/*
 * GeLU Lookup Table — auto-generated by gelu_lut_gen.py
 * {LUT_SIZE} entries covering [{LUT_MIN}, {LUT_MAX}], step = {step:.5f}
 * Formula: GeLU(x) = 0.5*x*(1 + tanh(sqrt(2/pi)*(x + 0.044715*x^3)))
 */
#define GELU_LUT_SIZE {LUT_SIZE}
#define GELU_LUT_MIN  ({LUT_MIN}f)
#define GELU_LUT_MAX  ({LUT_MAX}f)
#define GELU_LUT_STEP ({step:.8f}f)

static float gelu_lut[{LUT_SIZE}] = {{
{body}
}};

/*
 * geluLUT — evaluate GeLU via lookup table.
 * Boundary behaviour:
 *   x <= GELU_LUT_MIN  →  0.0f    (GeLU saturates near 0 for x << 0)
 *   x >= GELU_LUT_MAX  →  x       (GeLU ≈ identity for x >> 0)
 */
static float geluLUT(float x) {{
    if (x <= GELU_LUT_MIN) return 0.0f;
    if (x >= GELU_LUT_MAX) return x;
    int idx = (int)((x - GELU_LUT_MIN) / GELU_LUT_STEP);
    if (idx < 0)              idx = 0;
    if (idx >= GELU_LUT_SIZE) idx = GELU_LUT_SIZE - 1;
    return gelu_lut[idx];
}}

#endif /* GELU_LUT_H */
"""
    Path(output_path).write_text(header)
    print(f"GeLU LUT written → {output_path}  ({LUT_SIZE} entries, step={step:.5f})")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Generate GeLU LUT C header")
    p.add_argument("--output", default="gelu_lut.h", help="Output header path")
    args = p.parse_args()
    generate(args.output)
