"""
Generate a C header with a SiLU (Swish) lookup table for ESBMC verification.

SiLU(x) = x * sigmoid(x) = x / (1 + exp(-x))

Used in: LLaMA, Mistral, Falcon, Phi, and most recent open LLMs.

LUT covers [-8, 8] in LUT_SIZE steps.
  x < -8  →  returns 0.0   (SiLU saturates near 0 for very negative x)
  x >  8  →  returns x     (SiLU ≈ identity for large positive x)

Usage:
    python silu_lut_gen.py              # writes silu_lut.h
    python silu_lut_gen.py --output path.h
"""

import math
from pathlib import Path

LUT_MIN: float = -8.0
LUT_MAX: float = 8.0
LUT_SIZE: int = 1600   # step = 0.01


def _silu(x: float) -> float:
    return x / (1.0 + math.exp(-x))


def generate(output_path: str = "silu_lut.h") -> None:
    step = (LUT_MAX - LUT_MIN) / LUT_SIZE
    values = [_silu(LUT_MIN + i * step) for i in range(LUT_SIZE)]

    rows = []
    for i in range(0, LUT_SIZE, 8):
        chunk = values[i : i + 8]
        rows.append("    " + ", ".join(f"{v:.6f}f" for v in chunk))
    body = ",\n".join(rows)

    header = f"""\
#ifndef SILU_LUT_H
#define SILU_LUT_H

/*
 * SiLU (Swish) Lookup Table — auto-generated by silu_lut_gen.py
 * {LUT_SIZE} entries covering [{LUT_MIN}, {LUT_MAX}], step = {step:.5f}
 * Formula: SiLU(x) = x * sigmoid(x) = x / (1 + exp(-x))
 * Used in: LLaMA, Mistral, Falcon, Phi
 */
#define SILU_LUT_SIZE {LUT_SIZE}
#define SILU_LUT_MIN  ({LUT_MIN}f)
#define SILU_LUT_MAX  ({LUT_MAX}f)
#define SILU_LUT_STEP ({step:.8f}f)

static float silu_lut[{LUT_SIZE}] = {{
{body}
}};

/*
 * siluLUT — evaluate SiLU via lookup table.
 *   x <= SILU_LUT_MIN  →  0.0f
 *   x >= SILU_LUT_MAX  →  x
 */
static float siluLUT(float x) {{
    if (x <= SILU_LUT_MIN) return 0.0f;
    if (x >= SILU_LUT_MAX) return x;
    int idx = (int)((x - SILU_LUT_MIN) / SILU_LUT_STEP);
    if (idx < 0)              idx = 0;
    if (idx >= SILU_LUT_SIZE) idx = SILU_LUT_SIZE - 1;
    return silu_lut[idx];
}}

#endif /* SILU_LUT_H */
"""
    Path(output_path).write_text(header)
    print(f"SiLU LUT written → {output_path}  ({LUT_SIZE} entries, step={step:.5f})")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Generate SiLU LUT C header")
    p.add_argument("--output", default="silu_lut.h")
    args = p.parse_args()
    generate(args.output)
